### ISSUE TITLE
Support for OpenAPI 3.1.0

### ISSUE THREAD

**Issue by jeaf-anaptecs** [anaptecs/jeaf-generator#13]
## Feature Description
Even though OpenAPI 3.1 seems to be only a minor update it contains breaking changes.

## Tasks:
* Handle breaking required changes as described in: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
* OpenAPI 3.0 still needs to be supported

## Required Changes for OpenAPI 3.1
- [x] Removed `openAPIVersion` property from JMM. Info is now taken from Maven configuration.
- [x] Allow configuration of OpenAPI version in Maven configuration
- [x] Swap nullable for type arrays
- [x] Tweak `exclusiveMinimum` and `exclusiveMaximum`
- [x] Use `examples` not `example`
- [ ] Update documentation about stereotypes
